spring:
  application:
    name: stream.mattes.io
  cache:
    cache-names: youtube
    caffeine.spec: maximumSize=100,expireAfterWrite=60s
# secret properties
app:
  youtube:
    enabled: false
    client_id:
    client_secret:
    refresh_token:
